<a href="https://colab.research.google.com/github/TharinduniHerath/Deep_learning_assignment/blob/BI-LSTM/BI_LSTM_it22322708.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/DL_assignment/IMDB Dataset.csv')

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
### Drop NaN values
df = df.dropna()

In [6]:
### Get the independent Features
x = df.drop('sentiment', axis=1)

In [7]:
### Get the Dependent Feaatures
y=df['sentiment'].map({'positive':1, 'negative':0})

In [8]:
x.shape

(50000, 1)

In [9]:
y.shape

(50000,)

In [10]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

In [11]:
import tensorflow as tf

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [13]:
### Vocabulary size
voc_size = 5000

**One-Hot Representation**

In [14]:
messages = x.copy()

In [15]:
messages['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [16]:
messages.reset_index(inplace=True)

In [20]:
import re
import nltk
from nltk.corpus import stopwords
from tqdm import tqdm

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
### Data Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))
corpus = []
for i in tqdm(range(len(messages))):
  text = re.sub('<.*?>',  ' ', messages['review'][i])
  review = re.sub('[^a-zA-Z]', ' ', text)
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if word not in stop_words]
  review = ' '.join(review)
  corpus.append(review)

100%|██████████| 50000/50000 [02:22<00:00, 350.99it/s]

In [24]:
onehot_repr = [one_hot(words, voc_size)for words in corpus]
onehot_repr

[[618,
  471,
  3744,
  2328,
  4049,
  1466,
  1012,
  3185,
  3673,
  1858,
  458,
  3310,
  2445,
  4049,
  4931,
  924,
  1283,
  1880,
  953,
  3185,
  2343,
  1842,
  2745,
  868,
  2914,
  1573,
  120,
  868,
  2941,
  3969,
  245,
  3909,
  380,
  1880,
  2182,
  1575,
  3855,
  2343,
  2231,
  4049,
  397,
  4320,
  3732,
  4341,
  2704,
  3471,
  4435,
  4651,
  2679,
  4597,
  3864,
  4695,
  3485,
  3207,
  1475,
  1717,
  2106,
  77,
  3721,
  2778,
  3452,
  4129,
  3856,
  3864,
  425,
  2730,
  567,
  90,
  1257,
  313,
  4678,
  2295,
  2733,
  2924,
  791,
  1780,
  1488,
  2349,
  4570,
  3128,
  4769,
  4253,
  3644,
  4991,
  3569,
  2520,
  2421,
  868,
  2472,
  4357,
  1758,
  868,
  837,
  1135,
  4366,
  3164,
  3402,
  3667,
  4806,
  1135,
  4748,
  1135,
  2570,
  4049,
  286,
  4031,
  458,
  1466,
  1992,
  4928,
  2445,
  1071,
  3230,
  3569,
  978,
  2328,
  3471,
  4892,
  4049,
  1100,
  442,
  3452,
  4487,
  3911,
  1880,
  1880,
  2166,
  4561,
  1197,
  4992,
  3545,
  2339,
  3713,
  2044,
  4459,
  3644,
  1031,
  3223,
  2619,
  1647,
  2339,
  65,
  3207,
  1627,
  2472,
  4058,
  2797,
  4502,
  3207,
  4825,
  2328,
  4049,
  2743,
  1246,
  4900,
  2284,
  3478,
  4343,
  4459,
  4618,
  4362,
  3545],
 [2241,
  3981,
  3162,
  4339,
  4659,
  4781,
  1801,
  1213,
  260,
  4766,
  4398,
  4900,
  630,
  3515,
  1987,
  1222,
  66,
  436,
  2151,
  2533,
  1031,
  4263,
  2364,
  1885,
  1100,
  1009,
  4723,
  1313,
  2979,
  2859,
  3093,
  1693,
  240,
  3811,
  3951,
  1924,
  4928,
  1031,
  2111,
  2328,
  4149,
  4927,
  897,
  436,
  4245,
  3162,
  618,
  3908,
  4245,
  1248,
  214,
  1222,
  2359,
  956,
  425,
  3981,
  3310,
  1518,
  1197,
  808,
  3855,
  2012,
  4488,
  4659,
  1812,
  1344,
  80,
  3354,
  1827,
  1987,
  1571,
  1283,
  462,
  3082,
  474,
  953,
  1571,
  1926,
  474,
  290,
  3356,
  4140,
  2809,
  3586,
  1031,
  1438],
 [1181,
  2241,
  4741,
  2648,
  1213,
  990,
  2173,
  1365,
  3434,
  1466,
  3944,
  160,
  2328,
  3789,
  1573,
  1248,
  1014,
  4088,
  2283,
  3907,
  3138,
  1722,
  3208,
  1031,
  971,
  1967,
  3790,
  428,
  2743,
  2335,
  687,
  3818,
  4448,
  1645,
  1074,
  1181,
  238,
  2662,
  714,
  2875,
  1401,
  4107,
  3463,
  2730,
  2974,
  2201,
  2362,
  2622,
  618,
  2662,
  1248,
  632,
  837,
  3569,
  971,
  4769,
  691,
  1806,
  2705,
  3097,
  2292,
  2861,
  3692,
  1465,
  3185,
  717,
  2995,
  2690,
  4944,
  2743,
  2202,
  1056,
  4087,
  1505,
  4081,
  3229,
  92,
  4636,
  4159,
  3908,
  1248,
  1842,
  2859,
  3276],
 [2735,
  3274,
  3981,
  245,
  3285,
  4977,
  2279,
  1437,
  895,
  1621,
  1213,
  3245,
  446,
  3793,
  1652,
  1428,
  3285,
  2132,
  1246,
  1035,
  3713,
  2279,
  4233,
  458,
  1842,
  4943,
  4339,
  4592,
  2132,
  773,
  2249,
  2249,
  3245,
  1219,
  895,
  128,
  1321,
  1068,
  3277,
  214,
  3285,
  1437,
  3378,
  1399,
  4339,
  3767,
  2859,
  1996,
  3781,
  3245,
  681,
  2328,
  2249,
  2583,
  773,
  616,
  1031,
  3354,
  895,
  1900,
  1177,
  2230,
  3285,
  23],
 [169,
  2561,
  2362,
  1213,
  1641,
  4552,
  212,
  4339,
  2328,
  521,
  2561,
  3180,
  2974,
  664,
  4981,
  3264,
  465,
  3245,
  1757,
  1059,
  2974,
  1641,
  4698,
  4797,
  3793,
  4104,
  331,
  3328,
  4912,
  2378,
  4448,
  3354,
  3455,
  4808,
  2410,
  4314,
  3118,
  1213,
  4122,
  3701,
  4104,
  3138,
  640,
  22,
  618,
  22,
  618,
  4741,
  3028,
  3324,
  1585,
  618,
  1757,
  700,
  3071,
  4448,
  1186,
  2790,
  4339,
  3066,
  436,
  880,
  2323,
  2859,
  3793,
  2929,
  2413,
  2929,
  1951,
  3310,
  618,
  4459,
  2251,
  3164,
  4104,
  3898,
  2887,
  618,
  4849,
  4180,
  3864,
  3673,
  2801,
  272,
  3264,
  465,
  2523,
  2564,
  3781,
  618,
  2611,
  2833,
  3793,
  3328,
  891,
  2951,
  521,
  2561,
  2573,
  4898,
  341,
  2132,
  1488,
  3181,
  1446,
  2364,
  488,
  2282,
  2192,
  3364,
  3829,
  4516,
  4943,
  3138,
  956,
  3021,
  3974,
  521,
  2561,
  2951,
  3381,
  1827,
  2945,
  3324,
  204],
 [1143,
  1213,
  3573,
  3245,
  4707,
  2383,
  2399,
  2970,
  4743,
  177,
  2032,
  4309,
  4769,
  4459,
  1801,
  1461,
  3642,
  1213,
  386,
  632,
  397,
  4975,
  897,
  2744,
  2409,
  787,
  2270,
  4200,
  618,
  2979,
  2815,
  703,
  4837,
  2792,
  2225,
  3569,
  1068,
  2673,
  484,
  2517,
  4943,
  378,
  2328,
  2154,
  4852,
  2473,
  1858,
  2413,
  4305,
  1043,
  4068,
  1347,
  3014,
  3245],
 [3635,
  4991,
  1068,
  2859,
  1570,
  1722,
  3640,
  4957,
  1376,
  1999,
  4991,
  2744,
  706,
  2792,
  1224,
  4893,
  4479,
  1748,
  1034,
  3640,
  2348,
  719,
  4140,
  2901,
  721,
  3571,
  4122,
  1416,
  1740,
  4411,
  1562,
  2617,
  1034,
  4991,
  204,
  2413,
  448,
  4773,
  2200,
  4741,
  2249,
  4693,
  1068,
  3478,
  2730,
  2286,
  1034,
  2730,
  3245,
  4832,
  4741,
  1043,
  1100,
  2582,
  3569,
  4991,
  513,
  4265,
  2333,
  4448,
  1416,
  1740,
  143,
  4991,
  3728,
  4991,
  4599,
  4186,
  249,
  2894,
  3987,
  4592,
  1842,
  4599],
 [868,
  3520,
  1860,
  2678,
  2892,
  458,
  1466,
  458,
  632,
  929,
  3310,
  3184,
  868,
  2359,
  4689,
  3988,
  2529,
  4124,
  1558,
  3417,
  1213,
  1999,
  2979,
  2800,
  4253,
  868,
  4940,
  3246,
  1232,
  2484,
  897,
  4785,
  2484,
  4336,
  3487,
  4374,
  1878,
  1307,
  868,
  1143,
  2875,
  1466,
  2523,
  2465,
  1043,
  1249,
  2616,
  3055,
  2753,
  4516,
  525,
  4665,
  581,
  4907,
  2865,
  618,
  32,
  2741,
  2859,
  1491,
  1505,
  925,
  537,
  4592,
  4398,
  4639,
  1195,
  2753,
  4516,
  1967,
  868,
  3074,
  4797,
  868,
  3997,
  1043,
  2875,
  1466],
 [2208,
  4683,
  361,
  4339,
  880,
  4718,
  2328,
  4339,
  2484,
  2036,
  3642,
  4339,
  2979,
  618,
  2329,
  3997,
  4785,
  4140,
  4741,
  1693,
  2617,
  3825,
  891,
  1729,
  4339,
  4610,
  612,
  2157,
  1466,
  3354,
  2763,
  1336,
  1213,
  4339,
  880,
  3544,
  1071,
  4309,
  2533,
  65,
  1889,
  2859,
  3317,
  3608,
  4339,
  3310,
  178,
  4398,
  990,
  3950,
  1035,
  4253,
  2801,
  897,
  167,
  1757,
  4943,
  4662,
  3674,
  618,
  1035,
  357],
 [1068,
  2753,
  2431,
  3260,
  760,
  1068,
  3245,
  2690,
  1801,
  2362,
  3245,
  1586,
  3208,
  1229,
  1068,
  3908,
  1264],
 [2625,
  2955,
  618,
  4162,
  4339,
  4736,
  1025,
  4031,
  3261,
  4274,
  808,
  4280,
  3264,
  458,
  3261,
  4366,
  4689,
  3245,
  4337,
  2523,
  4842,
  3261,
  4689,
  3988,
  1125,
  3871,
  4339,
  4343,
  4769,
  4221,
  4366,
  4636,
  3138,
  139,
  940,
  4636,
  3386,
  4339,
  4991,
  2421,
  645,
  1401,
  422,
  3099,
  3781,
  735,
  772,
  983,
  3028,
  4545],
 [4928,
  3245,
  2149,
  3785,
  2792,
  1283,
  4180,
  3040,
  409,
  3640,
  1050,
  568,
  3015,
  3185,
  1466,
  4736,
  4736,
  2690,
  2792,
  1842,
  1464,
  3188,
  4339,
  734,
  2451,
  2875,
  3210,
  935,
  3668,
  1996,
  3245,
  3493,
  4364,
  719,
  2748,
  4944,
  193,
  580,
  42,
  1889,
  2132,
  3668,
  194,
  3317,
  2446,
  3448,
  4774,
  2295,
  632,
  1801,
  3496,
  1014,
  2362,
  334,
  1726,
  632,
  3142,
  4928,
  1359,
  2149,
  2362,
  4639,
  4137,
  2148,
  3370,
  1231,
  4339,
  3238,
  1641,
  3735,
  4448,
  2762,
  994,
  4943,
  4707,
  4943,
  4722,
  2926,
  1031,
  3351,
  935,
  3878],
 [1667,
  4180,
  4933,
  2811,
  204,
  2730,
  3513,
  3245,
  3333,
  4388,
  1667,
  618,
  2811,
  2558,
  1801,
  3185,
  3855,
  4253,
  2505,
  3357,
  2307,
  3208,
  2241,
  3208,
  2715,
  3793,
  3513,
  3713,
  2235,
  2038,
  932,
  4128,
  2459,
  507,
  387,
  2632,
  4917,
  4253,
  2505,
  3099,
  521,
  2811,
  2042,
  584,
  3013,
  2618,
  3829,
  2444,
  166,
  953,
  521,
  2811,
  767,
  2278,
  2414,
  3354,
  2117,
  1842,
  1178,
  3353,
  2406,
  819,
  708,
  1414,
  3441,
  2278,
  1178,
  4280,
  1967,
  258,
  4366,
  4180,
  3245,
  320,
  3490,
  1758,
  1068,
  2916,
  1288,
  3354,
  3353,
  2406,
  1851,
  1288,
  4109,
  1007,
  2918,
  409,
  3999,
  352,
  2523,
  3353,
  891,
  3245,
  4366,
  4294,
  3793,
  4375,
  2359,
  4267,
  3051,
  2707,
  1288,
  4129,
  4928,
  1288,
  458,
  1585,
  2720,
  2359,
  700,
  880,
  1068,
  677,
  352,
  3825,
  4339,
  3987,
  759,
  2859,
  36,
  1286,
  4336,
  3023,
  1106,
  3354,
  819,
  708,
  4943,
  183,
  1488,
  126,
  594,
  2231,
  897,
  1964,
  932,
  4128,
  2632,
  2777,
  3006,
  4622,
  2709,
  4343,
  3185,
  561,
  2444,
  681,
  1100,
  513,
  4484,
  4230,
  2283,
  3208,
  4627,
  4253,
  1538,
  2505,
  743,
  1758,
  1842,
  2582,
  4267,
  3051,
  2811,
  2844,
  1842,
  2859,
  3245,
  2335,
  498,
  3051,
  2811,
  4825,
  613,
  3208,
  3310,
  2111,
  3744,
  4991,
  2828,
  2811,
  2951,
  204,
  110,
  4339,
  513,
  2066,
  1621,
  1283,
  2707,
  2470,
  1205,
  594,
  2606,
  4962,
  1283,
  4274,
  4943,
  2622,
  3245,
  4253,
  2505,
  255,
  2658,
  3045,
  712,
  141,
  461,
  2582,
  4047,
  3070,
  1842,
  2042,
  2385,
  1288,
  4459,
  791,
  3748,
  4943,
  2582,
  3468,
  458,
  2278,
  4010,
  3131],
 [4516,
  3354,
  579,
  579,
  940,
  3863,
  772,
  2744,
  579,
  1248,
  1399,
  3099,
  2951,
  2442,
  3354,
  3573,
  579,
  700,
  700,
  3761,
  3609,
  3217,
  2775,
  3217,
  772,
  3099,
  3781,
  3471,
  761,
  2343,
  1758,
  844,
  907,
  3246,
  3246,
  167,
  2124,
  3728,
  2085,
  3358,
  21,
  4769,
  320,
  3174,
  1842,
  3569,
  3245,
  3569,
  1758,
  628],
 [2708,
  3245,
  2278,
  3207,
  1246,
  3020,
  618,
  2151,
  4510,
  4371,
  4933,
  3039,
  2484,
  3028,
  2951,
  3310,
  3245,
  1729,
  1427,
  1202,
  724,
  1504,
  3245,
  963,
  2280,
  1608],
 [3185,
  96,
  2553,
  1283,
  687,
  618,
  3252,
  2660,
  4662,
  4339,
  1992,
  3642,
  1925,
  1068,
  3452,
  2379,
  4339,
  2366,
  2982,
  3569,
  4977,
  3137,
  3138,
  4700,
  1761,
  2282,
  2245,
  4366,
  2465,
  4459,
  2329,
  618,
  1621,
  1731,
  929,
  2507,
  1150,
  3987,
  4964,
  2051,
  235,
  451,
  4421,
  1002,
  3643,
  307,
  2194,
  4596,
  3328,
  2595,
  270,
  963,
  3354,
  528,
  703,
  4398,
  618,
  2831,
  1068,
  2131,
  235,
  2484,
  3417,
  4339,
  1641,
  1805,
  3466,
  1272,
  2517,
  743,
  4059],
 [4339,
  1801,
  3919,
  618,
  2484,
  4339,
  3298,
  834,
  4535,
  4289,
  4339,
  1906,
  4507,
  4790,
  3353,
  2012,
  4516,
  2302,
  3972,
  1868,
  1615,
  2744,
  3185,
  2444,
  3138,
  1456,
  128,
  1558,
  237,
  2370,
  4253,
  2904,
  3115,
  4707,
  3236,
  2291,
  940,
  105,
  2010,
  4339,
  754,
  214,
  1737,
  2391,
  3569,
  2484,
  4339,
  3513,
  5,
  4289,
  2714,
  237,
  3448],
 [3245,
  1967,
  618,
  1964,
  3997,
  3245,
  2042,
  2529,
  4010,
  1621,
  618,
  3668,
  3028,
  2478,
  3138,
  3471,
  2921,
  994,
  618,
  1759,
  1621,
  3028,
  2239,
  3144,
  3972,
  4180,
  2484,
  2658,
  203,
  2133,
  1283,
  4280,
  692,
  3245,
  2117,
  4639,
  2774,
  4050,
  4950,
  4712,
  1283,
  3317,
  692,
  2329,
  1283,
  1801,
  4639,
  2774,
  3278,
  4413,
  618,
  312,
  881,
  2658,
  921,
  3673,
  1068,
  1888,
  3957,
  881,
  4042,
  1951,
  4631,
  2283,
  551,
  4339,
  3682,
  4592,
  3561,
  551,
  4836,
  413,
  1533,
  2707,
  2658,
  2608,
  3264,
  3455,
  4050,
  2264,
  4950,
  3417,
  1213,
  4358,
  1059,
  1186,
  1186,
  4211,
  4707,
  3728,
  1746,
  4211,
  4726,
  3245,
  1805,
  2132,
  2517,
  3245,
  4019,
  3245,
  3448,
  3753,
  3997,
  3277,
  2335,
  3569,
  167,
  1071,
  1641],
 [3321,
  4339,
  458,
  4339,
  2328,
  3558,
  3164,
  2767,
  272,
  173,
  706,
  4535,
  1641,
  983,
  3700,
  4836,
  3558,
  4836,
  1060,
  1369,
  3785,
  4191,
  2051,
  2706,
  4339,
  525,
  2749,
  2293,
  1356,
  2151,
  1356,
  2771,
  4977,
  618,
  4191,
  4459,
  2230,
  194,
  2565,
  700,
  2523,
  719,
  2898,
  2698,
  4599,
  700,
  3558,
  65,
  1491,
  745,
  4180,
  3201,
  2459,
  3558,
  235,
  3644,
  4991,
  2362,
  2008,
  1671,
  3642,
  4339,
  1068],
 [3997,
  4339,
  4592,
  3277,
  4238,
  1924,
  1838,
  2453,
  2323,
  4707,
  458,
  3020,
  2402,
  4041,
  4071,
  4355,
  3987,
  4810,
  4224,
  2323,
  4270,
  4357,
  4707,
  2951,
  4991,
  1080,
  168,
  1801,
  4700,
  4335,
  3051,
  4707,
  1498,
  4991,
  1967,
  4253,
  735,
  4339,
  956,
  369,
  198,
  1277,
  1761,
  452,
  4455,
  3793,
  42,
  237,
  1838,
  4090,
  3317,
  503,
  1498,
  214,
  1805,
  1071,
  316,
  384,
  4389,
  3364,
  4339,
  2942],
 [4797,
  194,
  2465,
  1844,
  3149,
  2359,
  3218,
  194,
  2465,
  3245,
  2460,
  12,
  1994,
  12,
  272,
  12,
  1213,
  1329,
  4477,
  194,
  2465,
  235,
  1213,
  3942,
  882,
  3036,
  1229,
  3468,
  1037,
  4087,
  4477,
  618,
  4180,
  170,
  1600,
  4488,
  134,
  3562,
  235,
  2493,
  1025,
  1465,
  1200,
  3317,
  1620,
  891,
  4502,
  1184,
  2891,
  1839,
  4339,
  618,
  985,
  1239,
  385,
  1037,
  3208,
  3097,
  4459,
  891,
  2525,
  352,
  1135,
  1002,
  4280,
  3066,
  1425,
  3487,
  707,
  498,
  392,
  105,
  334,
  392,
  2622,
  1100,
  2362,
  2843,
  4087,
  3217,
  36,
  3349,
  4140,
  3941,
  581,
  2348,
  2801,
  156,
  3915,
  676,
  3976,
  4681,
  4951,
  4042,
  1409,
  2743,
  728,
  4981,
  3790,
  428,
  2364,
  265,
  2922,
  1768,
  514,
  897,
  960,
  3639,
  2020,
  3552,
  1232,
  3102,
  3059,
  1427,
  4769,
  2963,
  74,
  4117,
  3635,
  2359,
  880,
  1068,
  623,
  3682,
  1559,
  3138,
  2768,
  4948,
  4351,
  791,
  3744,
  4592,
  1842,
  4487,
  2111,
  4314,
  2151,
  3258,
  550,
  2814,
  2484,
  1994,
  956,
  1596,
  4117,
  3855,
  960,
  3264,
  658,
  1851,
  1658,
  3513,
  4662,
  960,
  4411,
  2951,
  677,
  1135,
  735,
  2514,
  2446,
  1805,
  4769,
  1858,
  2034,
  891,
  3767,
  65,
  1297,
  3513,
  880,
  2743,
  618,
  3229,
  129],
 [3586,
  7,
  3478,
  3188,
  3245,
  1086,
  3569,
  1071,
  1213,
  1641,
  1100,
  2329,
  3188,
  3245,
  1213,
  3208,
  2231,
  3188,
  3245,
  1068,
  3880,
  3245,
  3298,
  216,
  4943,
  2951,
  3245,
  4707,
  4636,
  2151,
  3418,
  3344,
  1043,
  2484,
  2573,
  4314,
  1172,
  1148,
  4785,
  4689,
  4785,
  3245,
  3135,
  1184,
  2016,
  618,
  3288,
  1195,
  1585,
  1805,
  2523,
  2343,
  167,
  3981,
  4662,
  3245,
  1761,
  2789,
  1311,
  3640,
  3754,
  3013,
  3571,
  134,
  1801,
  1401,
  3310,
  956,
  1311,
  3317,
  772,
  2749,
  2861,
  3908,
  2042,
  2891,
  3298,
  2015,
  3208,
  4964,
  3188,
  3245,
  2875,
  4398,
  2622,
  1232,
  2328],
 [1977,
  212,
  3245,
  3499,
  3713,
  2328,
  3893,
  3448,
  378,
  1449,
  2537,
  3245,
  37,
  2791,
  2153,
  2875,
  1068,
  3359,
  461,
  3574,
  4047,
  1213,
  2306,
  4477,
  1213,
  2359,
  1538,
  1068],
 [458,
  4599,
  4459,
  3310,
  69,
  4284,
  4933,
  2012,
  3634,
  4357,
  3855,
  2328,
  1673,
  205,
  1213,
  37,
  3188,
  1068,
  1566,
  3188,
  3245,
  1759,
  759,
  1068,
  2249,
  3245,
  2051,
  423,
  3245,
  458,
  956,
  1757,
  1068,
  1842,
  3493,
  3188,
  3245,
  2016,
  4799,
  3097,
  1984,
  4284,
  956,
  3245,
  1758,
  522,
  2619,
  4284,
  2484,
  3544,
  3208,
  3517,
  3321,
  1673,
  205,
  1366,
  4357,
  3544,
  618,
  1283,
  3245,
  4800,
  3321,
  2923,
  2792,
  994,
  2379,
  2792,
  4799,
  3586,
  4490,
  880,
  3517,
  2249,
  1785,
  2877,
  2929,
  4314,
  4284,
  3583,
  2283,
  4723,
  134,
  3358,
  4442,
  3478,
  3763,
  1994,
  4535,
  4047,
  679,
  719,
  13,
  2117,
  3310,
  984,
  149,
  3195,
  4842,
  361,
  1068,
  4937,
  1709,
  4898,
  4508,
  2652,
  4192,
  3714,
  859,
  4741,
  4138,
  3513,
  3245,
  149,
  1213,
  3641,
  719,
  868,
  3028,
  30,
  648,
  2140,
  2760,
  4784,
  3188,
  3245,
  3663,
  752,
  4366,
  1232,
  2328,
  334,
  1759,
  1213,
  4398,
  3245,
  844,
  2753,
  1842,
  4398,
  1949,
  3749,
  4846,
  613,
  4366,
  3448,
  4309,
  2484,
  378,
  4842,
  2278,
  1891,
  2523,
  4741,
  4943,
  378,
  1246,
  378,
  4842],
 [2329,
  3245,
  4928,
  69,
  525,
  491,
  167,
  284,
  1580,
  3276,
  4977,
  491,
  4810,
  1025,
  284,
  1051,
  2151,
  4339,
  3908,
  2859,
  338,
  3694,
  3245,
  4010,
  2822,
  3448,
  735,
  1330,
  436,
  2744,
  3364,
  891,
  2465,
  3596,
  3245,
  4964,
  3496,
  2520,
  3138,
  3378,
  3639,
  4090,
  4309,
  2328,
  3277,
  2239,
  1851,
  4707,
  3245,
  567,
  2151,
  4459,
  204,
  2444,
  2753,
  3471,
  4742,
  2444,
  1068,
  618,
  2730,
  69,
  3472,
  3245,
  4928,
  706,
  3208,
  2951,
  618,
  1886],
 [4300,
  1165,
  4707,
  868,
  3981,
  4860,
  4300,
  1165,
  3292,
  214,
  2472,
  3298,
  4398,
  1332,
  4357,
  3727,
  3602,
  674,
  4185,
  4300,
  168,
  4967,
  2951,
  1330,
  3354,
  1081,
  1925,
  1897,
  4300,
  1165,
  4977,
  703,
  4411,
  3605,
  3138,
  4358,
  3605,
  1585,
  4615,
  3131,
  703,
  646,
  1165,
  4057,
  3908,
  1122,
  4300,
  2154,
  3908,
  4610,
  1805,
  4364,
  1729,
  689,
  4826,
  2472,
  3245,
  1964,
  3841,
  4668,
  1566,
  2157],
 [1475,
  4442,
  1420,
  4996,
  4605,
  924,
  1267,
  3790,
  428,
  525,
  618,
  3829,
  4808,
  4726,
  1881,
  823,
  3264,
  4765,
  2207,
  4427,
  3386,
  4899,
  204,
  1066,
  2461,
  1181,
  186,
  935,
  2276,
  246,
  3099,
  2979,
  1203,
  2801,
  3245,
  632,
  1722,
  4265,
  4548,
  4224,
  4339,
  2670,
  3463,
  3441,
  3308,
  4516,
  3138,
  2484,
  891,
  4867,
  3128,
  4339,
  978,
  4448,
  3245,
  2743,
  2987,
  2012,
  3259,
  3245,
  3555,
  2865,
  1475,
  3647,
  3117,
  3028,
  2413,
  3386,
  2662,
  3117,
  77,
  1059,
  4808,
  700,
  4981,
  203,
  1585,
  4991,
  2319,
  3028,
  3245,
  700,
  4991,
  2362,
  2859,
  4358,
  772,
  127,
  4477,
  2865,
  1842,
  4622,
  1267,
  3790,
  428,
  1851,
  3459,
  554,
  4662,
  272,
  1184,
  3245,
  772,
  823,
  4943,
  3790,
  428,
  3349,
  204,
  3298,
  1475,
  1689,
  2500,
  4320,
  4122,
  323,
  4982,
  4634,
  1267,
  3118,
  1269,
  2763,
  1766,
  4944,
  3013,
  1617,
  3634,
  1992,
  4280,
  1068,
  3245,
  402,
  2974,
  3448,
  2191,
  170,
  772,
  478,
  4440,
  3079,
  4280,
  4459,
  4962,
  1322,
  3028,
  681,
  905,
  2435,
  2206,
  4836,
  880,
  1068,
  2359,
  3357,
  3684,
  4536,
  3028,
  227,
  1475,
  203,
  4599,
  2859,
  4461,
  3793,
  1068,
  3051,
  1068,
  4214,
  3245,
  3245,
  3187,
  4056,
  4122,
  4990,
  4592,
  4599,
  4179,
  1801,
  4047,
  3735,
  4339,
  2767,
  868,
  3555,
  4388,
  2696,
  4403,
  4552,
  4622,
  1322,
  3028,
  4296,
  953,
  935,
  1801,
  2137,
  3149,
  4339,
  1641,
  425,
  1523,
  3633,
  2801,
  2891,
  2801,
  4808,
  1068,
  167,
  4459,
  1924,
  2801,
  3164,
  3735,
  3185,
  3876,
  1269,
  634,
  3569,
  4051,
  452,
  2708,
  1181,
  1475,
  3457,
  3245,
  3647,
  1267,
  2323,
  2241,
  787,
  1033,
  633,
  4991,
  2951,
  1213,
  4461,
  4339,
  3981,
  3448,
  3793,
  3246,
  3908,
  906,
  3448,
  1216,
  3386,
  3264,
  1267,
  3185,
  4191,
  249,
  160,
  4477,
  618,
  4806,
  2195,
  3569,
  2589,
  1967,
  3245,
  3635,
  2051,
  2951,
  3909,
  203,
  3368],
 [4339,
  772,
  2730,
  3310,
  3561,
  2470,
  2589,
  1917,
  305,
  2641,
  4774,
  1248,
  3274,
  2103,
  1486,
  800,
  1758,
  3298,
  2015,
  452,
  4636,
  3174,
  65,
  3317,
  2791,
  3863,
  2995,
  1235,
  2774,
  3913,
  1004,
  2859,
  4575,
  3674,
  134,
  2323,
  130,
  2022,
  4058,
  1877,
  211,
  1114,
  808,
  1801,
  4426,
  3246,
  2573,
  3162,
  624,
  4339,
  1114,
  1967,
  2824,
  2774,
  2041,
  378,
  4741,
  458,
  3051,
  2157,
  1858,
  2777,
  4662,
  2278,
  1951,
  4171,
  548,
  2575,
  177,
  462],
 [3245,
  2814,
  4274,
  1757,
  1018,
  3378,
  629,
  2951,
  1213,
  167,
  1181,
  2201,
  4194,
  12,
  458,
  3908,
  3262,
  1068,
  2328,
  2379,
  4347,
  425,
  3472,
  1898,
  895,
  4337,
  3448,
  874,
  4602,
  313,
  3274,
  4411,
  2510,
  1585,
  4143,
  4411,
  2865,
  3981,
  4948,
  2012,
  1470,
  4358,
  4337,
  3744,
  2329,
  1283,
  3612,
  4592,